from __future__ import annotations

import json
from pathlib import Path
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from .mrf_helper import Frame

import matplotlib.pyplot as plt

from ._script_builder import ScriptBuilder

"""
Generate tcl script for time history and pushover analysis using OpenSees
Writen by: Wenchen Lie
2024-03-17
"""


def _plain_number(value: int | float) -> str:
    """Format a physical model parameter without exponential notation."""
    magnitude = abs(float(value))
    if magnitude >= 1.0e6:
        decimal_places = 3
    elif magnitude >= 1.0:
        decimal_places = 9
    else:
        decimal_places = 12
    text = f"{float(value):.{decimal_places}f}".rstrip("0").rstrip(".")
    text = "0" if text in {"", "-0"} else text
    if isinstance(value, float) and "." not in text:
        text += ".0"
    return text


class ScriptWriter(ScriptBuilder):
    """Build and persist matching Tcl and OpenSeesPy model scripts."""

    def __init__(self, frame: Frame, *, overwrite: bool = True, show_plot: bool = False) -> None:
        self.frame = frame
        self.overwrite = overwrite
        self.show_plot = show_plot
        self.line_frag = dict()
        if not show_plot:
            plt.switch_backend("Agg")
        self.fig, self.ax = plt.subplots()
        super().__init__(self.ax)
        self.generated_files: dict[str, Path] = {}
        try:
            self._build()
            self.generated_files = self.save()
        finally:
            plt.close(self.fig)

    def _build(self) -> None:
        """Run the script sections in their required output order."""
        self.write_script()
        self.write_nodes()
        self.write_elements()
        self.write_constraint()
        self.write_recorders()
        self.write_mass()
        self.write_user_comments_tcl()
        self.write_user_comments_py()
        self.write_eigen()
        self.write_gravity()
        self.write_dynamic_analysis()
        self.write_pushover_analysis()
        self.write_cyclic_pushover()
        self.write_info()

    def write_script(self):
        frame = self.frame
        frame_name = frame.frame_name
        self.write("# " + "-" * 80)
        self.writepy("# " + "-" * 80, start="")
        s = f" {frame_name} ".center(80, "-")
        self.write("# " + s)
        self.writepy("# " + s, start="")
        s = f" Generated by: MRFHelper (Version {frame.version}) ".center(80, "-")
        self.write("# " + s)
        self.writepy("# " + s, start="")
        s = " (https://github.com/WenchenLie/MRFModeler) ".center(80, "-")
        self.write("# " + s)
        self.writepy("# " + s, start="")
        self.write("# " + "-" * 80)
        self.writepy("# " + "-" * 80, start="")
        self.write()
        self.write()
        self.writepy()
        self.writepy("import os", start="")
        self.writepy("import numpy as np", start="")
        self.writepy("from pathlib import Path", start="")
        self.writepy("import openseespy.opensees as ops", start="")
        self.writepy("from subroutines.BeamHinge import BeamHinge", start="")
        self.writepy("from subroutines.ColumnHinge import ColumnHinge", start="")
        self.writepy("from subroutines.PanelZone import PanelZone", start="")
        self.writepy("from subroutines.Spring_Zero import Spring_Zero", start="")
        self.writepy("from subroutines.Spring_Rigid import Spring_Rigid", start="")
        self.writepy("from subroutines.TimeHistorySolver import TimeHistorySolver", start="")
        self.writepy("from subroutines.PushoverAnalysis import PushoverAnalysis", start="")
        self.writepy("from subroutines.CyclicPushover import CyclicPushover", start="")
        self.writepy("from subroutines.DisplayModel2D import DisplayModel2D", start="")
        self.writepy("from math import pi", start="")
        self.writepy("from typing import Literal", start="")
        self.writepy()
        self.writepy()
        self.writepy("def run_openseespy(", start="")
        self.writepy("maxRunTime: float,")
        self.writepy('analysis_type: Literal["TH", "PO", "CP"],')
        self.writepy("ShowAnimation: Literal[True, False],")
        self.writepy("MPCO: Literal[True, False],")
        self.writepy("MainFolder: Path,")
        self.writepy("GMname: str,")
        self.writepy("SubFolder: Path,")
        self.writepy("GMdt: float,")
        self.writepy("GMpoints: int,")
        self.writepy("GMduration: float,")
        self.writepy("FVduration: float,")
        self.writepy("EqSF: float,")
        self.writepy("GMFile: Path,")
        self.writepy("maxRoofDrift: float,")
        self.writepy("CollapseDrift: float,")
        self.writepy("RDR_path: list[float]")
        self.writepy("):")
        self.writepy()
        self.write("wipe all;")
        self.writepy("ops.wipe()")
        self.write("model basic -ndm 2 -ndf 3;")
        self.writepy('ops.model("basic", "-ndm", 2, "-ndf", 3)')
        self.write()
        self.writepy()
        self.write("# Basic model variables")
        self.writepy("# Basic model variables")
        self.write("set maxRunTime 600.0;  # $$$")
        self.writepy("GMFile = GMFile.absolute().as_posix()")
        self.write('set analysis_type "TH";  # $$$')
        self.write("set ShowAnimation 1;  # $$$")
        self.write("set MPCO 0;  # $$$")
        self.write()
        self.write("# Ground motion information")
        self.write('set MainFolder "H:/MRF_results/test/4SMRF";  # $$$')
        line1 = self.Nlines
        self.write('set GMname "th5";  # $$$')
        self.write('set SubFolder "th5";  # $$$')
        self.write("set GMdt 0.01;  # $$$")
        self.write("set GMpoints 5590;  # $$$")
        self.write("set GMduration 55.89;  # $$$")
        self.write("set FVduration 30;  # $$$")
        self.write("set EqSF 2.0;  # $$$")
        self.write('set GMFile "F:/Projects/OpenSAS/GMs/$GMname.th";  # $$$')
        self.write('set subroutines "F:/Projects/OpenSAS/subroutines";  # $$$')
        self.write('set temp "F:/Projects/OpenSAS/temp";  # $$$')
        line2 = self.Nlines
        self.line_frag["gminfo"] = (line1, line2)
        self.write()
        self.writepy()
        self.write("# Sourcing subroutines")
        self.write("cd $subroutines;")
        self.write("source DisplayModel3D.tcl;")
        self.write("source DisplayPlane.tcl;")
        self.write("source Spring_Zero.tcl;")
        self.write("source Spring_Rigid.tcl;")
        self.write("source PanelZone.tcl")
        self.write("source BeamHinge.tcl")
        self.write("source ColumnHinge.tcl")
        self.write("source TimeHistorySolver.tcl;")
        self.write("source PushoverAnalysis.tcl;")
        self.write("source CyclicPushover.tcl;")
        self.write()
        self.write("# Results folders")
        self.writepy("# Results folders")
        self.write("file mkdir $MainFolder;")
        self.writepy("if not MainFolder.exists():")
        self.writepy("    os.mkdir(MainFolder)")
        self.write("file mkdir $MainFolder/$SubFolder;")
        self.writepy("if not (MainFolder/SubFolder).exists():")
        self.writepy("    os.mkdir(MainFolder/SubFolder)")
        self.write()
        self.writepy()
        self.write("# Basic parameters")
        self.writepy("# Basic parameters")
        self.write(f"set NStory {frame.N};")
        self.writepy(f"NStory = {frame.N}")
        self.write(f"set NBay {frame.bays};")
        self.writepy(f"NBay = {frame.bays}")
        self.write(f"set E {frame.load_and_material.elastic_modulus:.2f};")
        self.writepy(f"E = {frame.load_and_material.elastic_modulus:.2f}")
        self.write(f"set mu {frame.load_and_material.poisson_ratio};")
        self.writepy(f"mu = {frame.load_and_material.poisson_ratio}")
        self.write(f"set fy_beam {frame.load_and_material.fy_beam:.2f};")
        self.writepy(f"fy_beam = {frame.load_and_material.fy_beam:.2f}")
        self.write(f"set fy_column {frame.load_and_material.fy_column:.2f};")
        self.writepy(f"fy_column = {frame.load_and_material.fy_column:.2f}")
        self.write("uniaxialMaterial Elastic 9 1.e-9;")
        self.writepy('ops.uniaxialMaterial("Elastic", 9, 1.e-9)')
        self.write("uniaxialMaterial Elastic 99 1.e12;")
        self.writepy('ops.uniaxialMaterial("Elastic", 99, 1.e12)')
        self.write("geomTransf Linear 1;")
        self.writepy('ops.geomTransf("Linear", 1)')
        self.write("geomTransf PDelta 2;")
        self.writepy('ops.geomTransf("PDelta", 2)')
        self.write("geomTransf Corotational 3;")
        self.writepy('ops.geomTransf("Corotational", 3)')
        self.write("set A_Stiff 1.e8;")
        self.writepy("A_Stiff = 1.e8")
        self.write("set I_Stiff 1.e13;")
        self.writepy("I_Stiff = 1.e13")
        self.write()
        self.writepy()
        self.write("# Building geometry")
        self.writepy("# Building geometry")
        self.write("set Floor1 0.0;")
        self.writepy("Floor1 = 0.0")
        for floor in range(2, frame.N + 2):
            heigth = float(sum(frame.building_geometry.story_height[: floor - 1]))
            self.write(f"set Floor{floor} {heigth};")
            self.writepy(f"Floor{floor} = {heigth}")
        self.write()
        self.writepy(f"story_height = {frame.building_geometry.story_height}")
        self.writepy('np.savetxt(MainFolder/"heights.dat", story_height, fmt="%.2f")')
        self.writepy()
        self.write("set Axis1 0.0;")
        self.writepy("Axis1 = 0.0")
        d = 0
        for i, l_bay in enumerate(frame.building_geometry.bay_length):
            d += l_bay
            self.write(f"set Axis{i + 2} {float(d)};")
            self.writepy(f"Axis{i + 2} = {float(d)}")
        self.write(f"set Axis{i + 3} {float(d + l_bay)};")
        self.writepy(f"Axis{i + 3} = {float(d + l_bay)}")
        self.write()
        self.writepy()
        self.write(f"set HBuilding {float(frame.building_geometry.building_height)};")
        self.writepy(f"HBuilding = {float(frame.building_geometry.building_height)}")
        # self.write(f'variable HBuilding {float(frame.building_geometry.building_height)};')
        story_height = " ".join([str(i) for i in frame.building_geometry.story_height])
        self.write(f"set story_heights [list {story_height}];")
        self.write("set file_heights [open $MainFolder/heights.dat w]")
        self.write("foreach height $story_heights {\n    puts $file_heights $height\n}")
        self.write("close $file_heights")
        self.write()
        self.write()
        self.writepy()
        self.writepy()

    def write_nodes(self):
        """Write nodes
        * x_axis: x-coords of axes (including leaning column axis)
        * y_floor: y-coords of floor
        """
        frame = self.frame
        x_axis = [0]  # x-coord of axes
        for bay in frame.building_geometry.bay_length:
            x_axis.append(x_axis[-1] + bay)
        x_axis.append(x_axis[-1] + bay)
        y_floor = [0]
        for h in frame.building_geometry.story_height:
            y_floor.append(y_floor[-1] + h)
        s = " Nodes ".center(80, "-")
        self.write("# " + s)
        self.writepy("# " + s)
        self.write()
        self.writepy()

        # Support nodes
        self.write("# Support nodes")
        self.writepy("# Support nodes")
        for axis in range(1, len(x_axis) + 1):
            floor = 1
            x = x_axis[axis - 1]
            y = 0
            tag = self.get_id(10, floor, axis, 00)
            self.write(f"node {tag} $Axis{axis} $Floor1;")
            self.writepy(f"ops.node({tag}, Axis{axis}, Floor1)")
            self.node(x, y, node_id=tag)
        self.write("")
        self.writepy("")

        # Leaning column grid nodes
        self.write("# Leaning column grid nodes")
        self.writepy("# Leaning column grid nodes")
        for floor in range(2, self.frame.N + 2):
            axis = self.frame.axis + 1
            x = x_axis[-1]
            y = y_floor[floor - 1]
            tag = self.get_id(10, floor, axis, 00)
            self.write(f"node {tag} $Axis{axis} $Floor{floor};")
            self.writepy(f"ops.node({tag}, Axis{axis}, Floor{floor})")
            self.node(x, y, node_id=tag)
        self.write("")
        self.writepy("")

        # Leaning column connected nodes
        self.write("# Leaning column connected nodes")
        self.writepy("# Leaning column connected nodes")
        for floor in range(2, self.frame.N + 2):
            axis = self.frame.axis + 1
            x = x_axis[-1]
            y = y_floor[floor - 1]
            top_tag = self.get_id(10, floor, axis, 1)
            bottom_tag = self.get_id(10, floor, axis, 2)
            if floor != self.frame.N + 1:  # not top floor
                self.write(f"node {bottom_tag} $Axis{axis} $Floor{floor};")
                self.writepy(f"ops.node({bottom_tag}, Axis{axis}, Floor{floor})")
                self.write(f"node {top_tag} $Axis{axis} $Floor{floor};")
                self.writepy(f"ops.node({top_tag}, Axis{axis}, Floor{floor})")
                self.node(x, y, node_id=bottom_tag)
                self.node(x, y, node_id=top_tag)
            else:  # top floor
                self.write(f"node {bottom_tag} $Axis{axis} $Floor{floor};")
                self.writepy(f"ops.node({bottom_tag}, Axis{axis}, Floor{floor})")
                self.node(x, y, node_id=bottom_tag)
        self.write("")
        self.writepy("")

        # Moment frame column nodes
        self.write("# Moment frame column nodes")
        self.writepy("# Moment frame column nodes")
        for floor in range(1, self.frame.N + 2):
            temp_all = []
            temp_all_py = []
            temp_all_b, temp_all_t = [], []
            temp_all_b_py, temp_all_t_py = [], []
            if floor == 1:
                for axis in range(1, self.frame.axis + 1):
                    x, y = x_axis[axis - 1], 0
                    tag = self.get_id(10, floor, axis, 1)
                    temp_all.append(f"node {tag} $Axis{axis} $Floor{floor};")
                    temp_all_py.append(f"ops.node({tag}, Axis{axis}, Floor{floor})")
                    self.node(x, y, node_id=tag)
                self.write(*temp_all)
                self.writepy(*temp_all_py)
            elif floor == self.frame.N + 1:
                for axis in range(1, self.frame.axis + 1):
                    if axis == 1:
                        beam_h = self.frame.structural_components.beam_properties[floor][0][1]
                    elif axis == self.frame.axis:
                        beam_h = self.frame.structural_components.beam_properties[floor][-1][1]
                    else:
                        beam_h_left = self.frame.structural_components.beam_properties[floor][
                            axis - 2
                        ][1]
                        beam_h_right = self.frame.structural_components.beam_properties[floor][
                            axis - 1
                        ][1]
                        beam_h = (beam_h_left + beam_h_right) / 2
                    x, y = x_axis[axis - 1], y_floor[floor - 1] - beam_h / 2
                    tag = self.get_id(10, floor, axis, 2)
                    temp_all.append(
                        f"node {tag} $Axis{axis} [expr $Floor{floor} - {beam_h:.2f}/2];"
                    )
                    temp_all_py.append(
                        f"ops.node({tag}, Axis{axis}, Floor{floor} - {beam_h:.2f}/2)"
                    )
                    self.node(x, y, node_id=tag)
                self.write(*temp_all)
                self.writepy(*temp_all_py)
            else:
                for axis in range(1, self.frame.axis + 1):
                    if axis == 1:
                        beam_h = self.frame.structural_components.beam_properties[floor][0][1]
                    elif axis == self.frame.axis:
                        beam_h = self.frame.structural_components.beam_properties[floor][-1][1]
                    else:
                        beam_h_left = self.frame.structural_components.beam_properties[floor][
                            axis - 2
                        ][1]
                        beam_h_right = self.frame.structural_components.beam_properties[floor][
                            axis - 1
                        ][1]
                        beam_h = (beam_h_left + beam_h_right) / 2
                    x, y_b, y_t = (
                        x_axis[axis - 1],
                        y_floor[floor - 1] - beam_h / 2,
                        y_floor[floor - 1] + beam_h / 2,
                    )
                    bottom_tag, top_tag = (
                        self.get_id(10, floor, axis, 2),
                        self.get_id(10, floor, axis, 1),
                    )
                    temp_all_b.append(
                        f"node {bottom_tag} $Axis{axis} [expr $Floor{floor} - {beam_h:.2f}/2];"
                    )
                    temp_all_b_py.append(
                        f"ops.node({bottom_tag}, Axis{axis}, Floor{floor} - {beam_h:.2f}/2)"
                    )
                    temp_all_t.append(
                        f"node {top_tag} $Axis{axis} [expr $Floor{floor} + {beam_h:.2f}/2];"
                    )
                    temp_all_t_py.append(
                        f"ops.node({top_tag}, Axis{axis}, Floor{floor} + {beam_h:.2f}/2)"
                    )
                    self.node(x, y_b, node_id=bottom_tag)
                    self.node(x, y_t, node_id=top_tag)
                self.write(*temp_all_b)
                self.writepy(*temp_all_b_py)
                self.write(*temp_all_t)
                self.writepy(*temp_all_t_py)
        self.write("")
        self.writepy("")

        # Moment frame beam nodes
        self.write("# Moment frame beam nodes")
        self.writepy("# Moment frame beam nodes")
        for floor in range(2, frame.N + 2):
            write_temp = []
            write_temp_py = []
            story_bottom = floor - 1
            for bay in range(1, frame.bays + 1):
                h_col_l = frame.structural_components.column_properties[story_bottom][bay - 1][1]
                h_col_r = frame.structural_components.column_properties[story_bottom][bay][1]
                if story_bottom in frame.structural_components.column_splice:
                    # If splice exists, column depth is obtained from the upper floor
                    h_col_l = frame.structural_components.column_properties[story_bottom + 1][
                        bay - 1
                    ][1]
                    h_col_r = frame.structural_components.column_properties[story_bottom + 1][bay][
                        1
                    ]
                hinge_offset_l = (
                    h_col_l / 2 + frame.structural_components.rbs_length[floor][(bay - 1) * 2]
                )
                hinge_offset_r = (
                    h_col_r / 2 + frame.structural_components.rbs_length[floor][(bay - 1) * 2 + 1]
                )
                x_l, x_r, y = (
                    x_axis[bay - 1] + hinge_offset_l,
                    x_axis[bay] - hinge_offset_r,
                    y_floor[floor - 1],
                )
                left_tag, right_tag = (
                    self.get_id(10, floor, bay, 4),
                    self.get_id(10, floor, bay + 1, 5),
                )
                write_temp.append(
                    f"node {left_tag} [expr $Axis{bay} + {hinge_offset_l:.2f}] $Floor{floor};"
                )
                write_temp_py.append(
                    f"ops.node({left_tag}, Axis{bay} + {hinge_offset_l:.2f}, Floor{floor})"
                )
                write_temp.append(
                    f"node {right_tag} [expr $Axis{bay + 1} - {hinge_offset_r:.2f}] $Floor{floor};"
                )
                write_temp_py.append(
                    f"ops.node({right_tag}, Axis{bay + 1} - {hinge_offset_r:.2f}, Floor{floor})"
                )
                self.node(x_l, y, node_id=left_tag)
                self.node(x_r, y, node_id=right_tag)
            self.write(*write_temp)
            self.writepy(*write_temp_py)
        self.write("")
        self.writepy("")

        # Beam spring nodes
        self.write(
            "# Beam spring nodes (If RBS length equal zero, beam spring nodes will not be generated)"
        )
        self.writepy(
            "# Beam spring nodes (If RBS length equal zero, beam spring nodes will not be generated)"
        )
        for floor in range(2, frame.N + 2):
            write_temp = []
            write_temp_py = []
            story_bottom = floor - 1
            for bay in range(1, frame.bays + 1):
                h_col_l = frame.structural_components.column_properties[story_bottom][bay - 1][1]
                h_col_r = frame.structural_components.column_properties[story_bottom][bay][1]
                if story_bottom in frame.structural_components.column_splice:
                    # If splice exists, column depth is obtained from the upper floor
                    h_col_l = frame.structural_components.column_properties[story_bottom + 1][
                        bay - 1
                    ][1]
                    h_col_r = frame.structural_components.column_properties[story_bottom + 1][bay][
                        1
                    ]
                rbs_length_left = frame.structural_components.rbs_length[floor][(bay - 1) * 2]
                rbs_length_right = frame.structural_components.rbs_length[floor][(bay - 1) * 2 + 1]
                hinge_offset_l = h_col_l / 2 + rbs_length_left
                hinge_offset_r = h_col_r / 2 + rbs_length_right
                x_l, x_r, y = (
                    x_axis[bay - 1] + hinge_offset_l,
                    x_axis[bay] - hinge_offset_r,
                    y_floor[floor - 1],
                )
                left_tag, right_tag = (
                    self.get_id(10, floor, bay, 3),
                    self.get_id(10, floor, bay + 1, 6),
                )
                if rbs_length_left != 0:
                    write_temp.append(
                        f"node {left_tag} [expr $Axis{bay} + {hinge_offset_l:.2f}] $Floor{floor};"
                    )
                    write_temp_py.append(
                        f"ops.node({left_tag}, Axis{bay} + {hinge_offset_l:.2f}, Floor{floor})"
                    )
                    self.node(x_l, y, node_id=left_tag)
                if rbs_length_right != 0:
                    write_temp.append(
                        f"node {right_tag} [expr $Axis{bay + 1} - {hinge_offset_r:.2f}] $Floor{floor};"
                    )
                    write_temp_py.append(
                        f"ops.node({right_tag}, Axis{bay + 1} - {hinge_offset_r:.2f}, Floor{floor})"
                    )
                    self.node(x_r, y, node_id=right_tag)
            self.write(*write_temp)
            self.writepy(*write_temp_py)
        self.write("")
        self.writepy("")

        # column splice ndoes
        self.write("# Column splice ndoes")
        self.writepy("# Column splice ndoes")
        for story in range(1, frame.N + 1):
            if story in frame.structural_components.column_splice:
                write_temp = []
                write_temp_py = []
                for axis in range(1, frame.axis + 1):
                    story_height = frame.building_geometry.story_height[story - 1]
                    x = x_axis[axis - 1]
                    y = y_floor[story - 1] + story_height / 2
                    tag = self.get_id(10, story, axis, 7)
                    write_temp.append(
                        f"node {tag} $Axis{axis} [expr $Floor{story} + 0.5 * {story_height:.2f}];"
                    )
                    write_temp_py.append(
                        f"ops.node({tag}, Axis{axis}, Floor{story} + 0.5 * {story_height:.2f})"
                    )
                    self.node(x, y, node_id=tag)
                self.write(*write_temp)
                self.writepy(*write_temp_py)
        self.write("")
        self.writepy("")

        # beam splice ndoes
        self.write("# Beam splice ndoes")
        self.writepy("# Beam splice ndoes")
        for floor in range(2, frame.N + 2):
            # if floor in frame.structural_components.beam_splice:
            write_temp = []
            write_temp_py = []
            for bay in range(1, frame.bays + 1):
                if bay in frame.structural_components.beam_splice:
                    x = (x_axis[bay - 1] + x_axis[bay]) / 2
                    y = y_floor[floor - 1]
                    tag = self.get_id(10, floor, bay, 8)
                    bay_length = frame.building_geometry.bay_length[bay - 1]
                    write_temp.append(
                        f"node {tag} [expr $Axis{bay} + {bay_length:.2f} / 2] $Floor{floor};"
                    )
                    write_temp_py.append(
                        f"ops.node({tag}, Axis{bay} + {bay_length:.2f} / 2, Floor{floor})"
                    )
                    self.node(x, y, node_id=tag)
            self.write(*write_temp)
            self.writepy(*write_temp_py)
        self.write("")
        self.write("")
        self.writepy("")
        self.writepy("")

    def write_elements(self):
        frame = self.frame
        x_axis = [0]  # x-coord of axes
        for bay in frame.building_geometry.bay_length:
            x_axis.append(x_axis[-1] + bay)
        x_axis.append(x_axis[-1] + bay)
        y_floor = [0]  # y-coord of floors
        for h in frame.building_geometry.story_height:
            y_floor.append(y_floor[-1] + h)
        s = " Elements ".center(80, "-")
        self.write("# " + s)
        self.writepy("# " + s)
        self.write()
        self.writepy()

        # Stiffness modification
        self.write("set n 10.;")
        self.writepy("n = 10.")
        self.write()
        self.writepy()

        # Columns
        self.write("# Column elements")
        self.writepy("# Column elements")
        for story in range(1, frame.N + 1):
            write_temp = []
            write_temp_py = []
            write_temp_b, write_temp_t = [], []
            write_temp_b_py, write_temp_t_py = [], []
            for axis in range(1, frame.structural_components.axis + 1):
                area = frame.structural_components.column_properties[story][axis - 1][5]
                inertia = frame.structural_components.column_properties[story][axis - 1][6]
                if story not in frame.structural_components.column_splice:
                    # no column splice in this story
                    inode = self.get_id(10, story, axis, 1)
                    jnode = self.get_id(10, story + 1, axis, 2)
                    tag = self.get_id(10, story, axis, 1)
                    write_temp.append(
                        f"element elasticBeamColumn {tag} {inode} {jnode} {area:.2f} $E [expr ($n+1)/$n*{inertia:.2f}] 2;"
                    )
                    write_temp_py.append(
                        f'ops.element("elasticBeamColumn", {tag}, {inode}, {jnode}, {area:.2f}, E, (n+1)/n*{inertia:.2f}, 2)'
                    )
                    self.ele(inode, jnode, "blue", element_id=tag)
                else:
                    # column splices exist in this story
                    inode = self.get_id(10, story, axis, 1)
                    area_top = frame.structural_components.column_properties[story + 1][axis - 1][5]
                    inertia_top = frame.structural_components.column_properties[story + 1][
                        axis - 1
                    ][6]
                    midnode = self.get_id(10, story, axis, 7)
                    jnode = self.get_id(10, story + 1, axis, 2)
                    bottom_tag = self.get_id(10, story, axis, 2)
                    top_tag = self.get_id(10, story, axis, 3)
                    write_temp_b.append(
                        f"element elasticBeamColumn {bottom_tag} {inode} {midnode} {area:.2f} $E [expr ($n+1)/$n*{inertia:.2f}] 2;"
                    )
                    write_temp_b_py.append(
                        f'ops.element("elasticBeamColumn", {bottom_tag}, {inode}, {midnode}, {area:.2f}, E, (n+1)/n*{inertia:.2f}, 2)'
                    )
                    write_temp_t.append(
                        f"element elasticBeamColumn {top_tag} {midnode} {jnode} {area_top:.2f} $E [expr ($n+1)/$n*{inertia_top:.2f}] 2;"
                    )
                    write_temp_t_py.append(
                        f'ops.element("elasticBeamColumn", {top_tag}, {midnode}, {jnode}, {area_top:.2f}, E, (n+1)/n*{inertia_top:.2f}, 2)'
                    )
                    self.ele(inode, midnode, element_id=bottom_tag)
                    self.ele(midnode, jnode, element_id=top_tag)
            if write_temp:
                self.write(*write_temp)
                self.writepy(*write_temp_py)
            if write_temp_b:
                self.write(*write_temp_b)
                self.writepy(*write_temp_b_py)
                self.write(*write_temp_t)
                self.writepy(*write_temp_t_py)
        self.write("")
        self.writepy("")

        # beam element
        self.write("# Beam elements")
        self.writepy("# Beam elements")
        for floor in range(2, frame.N + 2):
            write_temp = []
            write_temp_py = []
            for bay in range(1, frame.bays + 1):
                area = frame.structural_components.beam_properties[floor][bay - 1][5]
                inertia = frame.structural_components.beam_properties[floor][bay - 1][6]
                midnode = self.get_id(10, floor, bay, 8)
                inode = self.get_id(10, floor, bay, 4)
                jnode = self.get_id(10, floor, bay + 1, 5)
                if int(midnode) in self.nodes_Id:
                    # beam splice exists
                    left_tag = self.get_id(10, floor, bay, 11)
                    right_tag = self.get_id(10, floor, bay, 12)
                    write_temp.append(
                        f"element elasticBeamColumn {left_tag} {inode} {midnode} {area:.2f} $E [expr ($n+1)/$n*{inertia:.2f}] 2;"
                    )
                    write_temp_py.append(
                        f'ops.element("elasticBeamColumn", {left_tag}, {inode}, {midnode}, {area:.2f}, E, (n+1)/n*{inertia:.2f}, 2)'
                    )
                    write_temp.append(
                        f"element elasticBeamColumn {right_tag} {midnode} {jnode} {area:.2f} $E [expr ($n+1)/$n*{inertia:.2f}] 2;"
                    )
                    write_temp_py.append(
                        f'ops.element("elasticBeamColumn", {right_tag}, {midnode}, {jnode}, {area:.2f}, E, (n+1)/n*{inertia:.2f}, 2)'
                    )
                    self.ele(inode, midnode, element_id=left_tag)
                    self.ele(midnode, jnode, element_id=right_tag)
                else:
                    # beam splice not exists
                    tag = self.get_id(10, floor, bay, 4)
                    write_temp.append(
                        f"element elasticBeamColumn {tag} {inode} {jnode} {area:.2f} $E [expr ($n+1)/$n*{inertia:.2f}] 2;"
                    )
                    write_temp_py.append(
                        f'ops.element("elasticBeamColumn", {tag}, {inode}, {jnode}, {area:.2f}, E, (n+1)/n*{inertia:.2f}, 2)'
                    )
                    self.ele(inode, jnode, element_id=tag)
            self.write(*write_temp)
            self.writepy(*write_temp_py)
        self.write()
        self.writepy()

        # Panel zones
        self.write("# Panel zones")
        self.writepy("# Panel zones")
        self.write(
            '# PanelNone Floor Axis X Y E mu fy_column A_stiff I_stiff d_col d_beam tp tf bf transfTag type_ position check ""'
        )
        self.writepy(
            "# PanelNone(Floor, Axis, X, Y, E, mu, fy_column, A_stiff, I_stiff, d_col, d_beam, tp, tf, bf, transfTag, type_, position, check=None)"
        )
        for floor in range(2, frame.N + 2):
            write_temp = []
            write_temp_py = []
            for axis in range(1, frame.axis + 1):
                story = floor - 1
                x = x_axis[axis - 1]
                y = y_floor[floor - 1]
                if axis == 1 and floor == frame.N + 1:
                    position = "LT"
                elif axis == frame.axis and floor == frame.N + 1:
                    position = "RT"
                elif axis == 1 and floor < frame.N + 1:
                    position = "L"
                elif axis == frame.axis and floor < frame.N + 1:
                    position = "R"
                elif 1 < axis < frame.axis and floor == frame.N + 1:
                    position = "T"
                else:
                    position = "I"
                d_col = frame.structural_components.column_properties[story][axis - 1][1]
                bf_col = frame.structural_components.column_properties[story][axis - 1][0]
                tf_col = frame.structural_components.column_properties[story][axis - 1][3]
                if story in frame.structural_components.column_splice:
                    d_col = frame.structural_components.column_properties[story + 1][axis - 1][1]
                    bf_col = frame.structural_components.column_properties[story + 1][axis - 1][0]
                    tf_col = frame.structural_components.column_properties[story + 1][axis - 1][3]
                if axis == 1:
                    d_beam = frame.structural_components.beam_properties[floor][0][1]
                elif axis == frame.axis:
                    d_beam = frame.structural_components.beam_properties[floor][-1][1]
                else:
                    d_beam_l = frame.structural_components.beam_properties[floor][axis - 2][1]
                    d_beam_r = frame.structural_components.beam_properties[floor][axis - 1][1]
                    d_beam = (d_beam_l + d_beam_r) / 2
                tp = frame.structural_components.pz_thickness[floor][axis - 1]
                type_ = 1 if frame.connection_and_boundary.panel_zone_deformation else 2
                self.add_panel_zone(floor, axis, x, y, d_col, d_beam, type_, position)
                write_temp.append(
                    f'PanelZone {floor} {axis} $Axis{axis} $Floor{floor} $E $mu $fy_column $A_Stiff $I_Stiff {d_col:.2f} {d_beam:.2f} {tp:.2f} {tf_col:.2f} {bf_col:.2f} 2 {type_} "{position}";'
                )
                write_temp_py.append(
                    f'PanelZone({floor}, {axis}, Axis{axis}, Floor{floor}, E, mu, fy_column, A_Stiff, I_Stiff, {d_col:.2f}, {d_beam:.2f}, {tp:.2f}, {tf_col:.2f}, {bf_col:.2f}, 2, {type_}, "{position}")'
                )
            self.write(*write_temp)
            self.writepy(*write_temp_py)
        self.write()
        self.writepy()

        # RBS element
        self.write("# RBS elements (If RBS length equal zero, RBS element will not be generated)")
        self.writepy("# RBS elements (If RBS length equal zero, RBS element will not be generated)")
        for floor in range(2, frame.N + 2):
            write_temp = []
            write_temp_py = []
            for bay in range(1, frame.bays + 1):
                axis_left, axis_right = bay, bay + 1
                area = frame.structural_components.beam_properties[floor][bay - 1][5]
                inertia = frame.structural_components.beam_properties[floor][bay - 1][6]
                # bay left
                inode = self.get_id(11, floor, axis_left, 4)
                jnode = self.get_id(10, floor, axis_left, 3)
                if jnode in self.nodes_Id:
                    tag = self.get_id(10, floor, bay, 5)
                    write_temp.append(
                        f"element elasticBeamColumn {tag} {inode} {jnode} {area:.2f} $E {inertia:.2f} 2;"
                    )
                    write_temp_py.append(
                        f'ops.element("elasticBeamColumn", {tag}, {inode}, {jnode}, {area:.2f}, E, {inertia:.2f}, 2)'
                    )
                    self.ele(inode, jnode, element_id=tag)
                # right bay
                inode = self.get_id(10, floor, axis_right, 6)
                jnode = self.get_id(11, floor, axis_right, 2)
                if inode in self.nodes_Id:
                    tag = self.get_id(10, floor, bay, 6)
                    write_temp.append(
                        f"element elasticBeamColumn {tag} {inode} {jnode} {area:.2f} $E {inertia:.2f} 2;"
                    )
                    write_temp_py.append(
                        f'ops.element("elasticBeamColumn", {tag}, {inode}, {jnode}, {area:.2f}, E, {inertia:.2f}, 2)'
                    )
                    self.ele(inode, jnode, element_id=tag)
            self.write(*write_temp)
            self.writepy(*write_temp_py)
        self.write()
        self.writepy()

        # Beam hinge
        self.write("# Beam hinges")
        self.writepy("# Beam hinges")
        self.write(
            '# BeamHinge SpringID NodeI NodeJ E fy_beam Ix d htw bftf ry L Ls Lb My type_ {check ""}'
        )
        self.writepy(
            "# BeamHinge(SpringID, NodeI, NodeJ, E, fy_beam, Ix, d htw bftf ry L Ls Lb My type_, check=None)"
        )
        for floor in range(2, frame.N + 2):
            write_temp = []
            write_temp_py = []
            for bay in range(1, frame.bays + 1):
                axis_left, axis_right = bay, bay + 1
                story_bottom, story_top = floor - 1, floor
                ix = frame.structural_components.beam_properties[floor][bay - 1][6]
                d = frame.structural_components.beam_properties[floor][bay - 1][1]
                tw = frame.structural_components.beam_properties[floor][bay - 1][2]
                h = frame.structural_components.beam_properties[floor][bay - 1][8]
                htw = h / tw
                bf = frame.structural_components.beam_properties[floor][bay - 1][0]
                tf = frame.structural_components.beam_properties[floor][bay - 1][3]
                bftf = bf / (2 * tf)
                ry = frame.structural_components.beam_properties[floor][bay - 1][4]
                d_col_l = frame.structural_components.column_properties[story_bottom][
                    axis_left - 1
                ][1]
                d_col_r = frame.structural_components.column_properties[story_bottom][
                    axis_right - 1
                ][1]
                if story_bottom in frame.structural_components.column_splice:
                    d_col_l = frame.structural_components.column_properties[story_top][
                        axis_left - 1
                    ][1]
                    d_col_r = frame.structural_components.column_properties[story_top][
                        axis_right - 1
                    ][1]
                bay_length = frame.building_geometry.bay_length[bay - 1]
                length = bay_length - (d_col_l + d_col_r) / 2
                shear_length, unbraced_length = length / 2, length / 2
                yield_moment = frame.structural_components.beam_properties[floor][bay - 1][7]
                if frame.connection_and_boundary.beam_column_connection == "Full":
                    type_ = 2
                elif frame.connection_and_boundary.beam_column_connection == "RBS":
                    type_ = 1
                elif frame.connection_and_boundary.beam_column_connection == "Hinged":
                    type_ = 3
                # left hinge
                tag = self.get_id(10, floor, axis_left, 9)
                inode1 = self.get_id(11, floor, axis_left, 4)
                inode2 = self.get_id(10, floor, axis_left, 3)
                if inode2 in self.nodes_Id:
                    # RBS
                    inode = inode2
                else:
                    # Other than RBS
                    inode = inode1
                jnode = self.get_id(10, floor, axis_left, 4)
                write_temp.append(
                    f"BeamHinge {tag} {inode} {jnode} $E $fy_beam {ix:.2f} {d:.2f} {htw:.2f} {bftf:.2f} {ry:.2f} {length:.1f} {shear_length:.1f} {unbraced_length:.1f} {yield_moment:.2f} {type_};"
                )
                write_temp_py.append(
                    f"BeamHinge({tag}, {inode}, {jnode}, E, fy_beam, {ix:.2f}, {d:.2f}, {htw:.2f}, {bftf:.2f}, {ry:.2f}, {length:.1f}, {shear_length:.1f}, {unbraced_length:.1f}, {yield_moment:.2f}, {type_})"
                )
                self.zero_length(inode, jnode, element_id=tag)
                # right hinge
                tag = self.get_id(10, floor, axis_right, 10)
                inode = self.get_id(10, floor, axis_right, 5)
                jnode1 = self.get_id(10, floor, axis_right, 6)
                jnode2 = self.get_id(11, floor, axis_right, 2)
                if jnode1 in self.nodes_Id:
                    # RBS
                    jnode = jnode1
                else:
                    # Other than RBS
                    jnode = jnode2
                write_temp.append(
                    f"BeamHinge {tag} {inode} {jnode} $E $fy_beam {ix:.2f} {d:.2f} {htw:.2f} {bftf:.2f} {ry:.2f} {length:.1f} {shear_length:.1f} {unbraced_length:.1f} {yield_moment:.2f} {type_};"
                )
                write_temp_py.append(
                    f"BeamHinge({tag}, {inode}, {jnode}, E, fy_beam, {ix:.2f}, {d:.2f}, {htw:.2f}, {bftf:.2f}, {ry:.2f}, {length:.1f}, {shear_length:.1f}, {unbraced_length:.1f}, {yield_moment:.2f}, {type_})"
                )
                self.zero_length(inode, jnode, element_id=tag)
            self.write(*write_temp)
            self.writepy(*write_temp_py)
        self.write()
        self.writepy()

        # column hinges
        self.write("# Column hinges")
        self.writepy("# Column hinges")
        self.write('# Column SpringID NodeI NodeJ E Ix d htw ry L Lb My PPy SF_PPy pinned check ""')
        self.writepy(
            "# Column(SpringID, NodeI, NodeJ, E, Ix, d, htw, ry, L, Lb, My, PPy, SF_PPy, pinned, check=None)"
        )
        for story in range(1, frame.N + 1):
            write_temp_b = []
            write_temp_b_py = []
            write_temp_t = []
            write_temp_t_py = []
            for axis in range(1, frame.axis + 1):
                floor_bottom, floor_top = story, story + 1
                bay_left, bay_right = axis - 1, axis
                inertia_bottom = frame.structural_components.column_properties[story][axis - 1][6]
                d_b = frame.structural_components.column_properties[story][axis - 1][1]
                tw_b = frame.structural_components.column_properties[story][axis - 1][2]
                h_b = frame.structural_components.column_properties[story][axis - 1][8]
                htw_b = h_b / tw_b
                ry_b = frame.structural_components.column_properties[story][axis - 1][4]
                if story in frame.structural_components.column_splice:
                    inertia_top = frame.structural_components.column_properties[story + 1][
                        axis - 1
                    ][6]
                    d_t = frame.structural_components.column_properties[story + 1][axis - 1][1]
                    tw_t = frame.structural_components.column_properties[story + 1][axis - 1][2]
                    h_t = frame.structural_components.column_properties[story + 1][axis - 1][8]
                    htw_t = h_t / tw_t
                    ry_t = frame.structural_components.column_properties[story + 1][axis - 1][4]
                else:
                    inertia_top = inertia_bottom
                    d_t = d_b
                    tw_t = tw_b
                    h_t = h_b
                    htw_t = htw_b
                    ry_t = ry_b
                if floor_bottom == 1:
                    d_beam_b_l = 0
                    d_beam_b_r = 0
                else:
                    if axis == 1:
                        d_beam_b_l = frame.structural_components.beam_properties[floor_bottom][0][1]
                        d_beam_b_r = frame.structural_components.beam_properties[floor_bottom][0][1]
                    elif axis == frame.axis:
                        d_beam_b_l = frame.structural_components.beam_properties[floor_bottom][-1][
                            1
                        ]
                        d_beam_b_r = frame.structural_components.beam_properties[floor_bottom][-1][
                            1
                        ]
                    else:
                        d_beam_b_l = frame.structural_components.beam_properties[floor_bottom][
                            bay_left - 1
                        ][1]
                        d_beam_b_r = frame.structural_components.beam_properties[floor_bottom][
                            bay_right - 1
                        ][1]
                if axis == 1:
                    d_beam_t_l = frame.structural_components.beam_properties[floor_top][0][1]
                    d_beam_t_r = frame.structural_components.beam_properties[floor_top][0][1]
                elif axis == frame.axis:
                    d_beam_t_l = frame.structural_components.beam_properties[floor_top][-1][1]
                    d_beam_t_r = frame.structural_components.beam_properties[floor_top][-1][1]
                else:
                    d_beam_t_l = frame.structural_components.beam_properties[floor_top][
                        bay_left - 1
                    ][1]
                    d_beam_t_r = frame.structural_components.beam_properties[floor_top][
                        bay_right - 1
                    ][1]
                story_length = frame.building_geometry.story_height[story - 1]
                length = (
                    story_length - (d_beam_b_l + d_beam_b_r) / 4 - (d_beam_t_l + d_beam_t_r) / 4
                )
                unbraced_length = length
                yield_moment_bottom = frame.structural_components.column_properties[story][
                    axis - 1
                ][7]
                if story not in frame.structural_components.column_splice:
                    yield_moment_top = yield_moment_bottom
                else:
                    yield_moment_top = frame.structural_components.column_properties[story + 1][
                        axis - 1
                    ][7]
                axial_load_ratio_bottom = frame.load_and_material.ppy[f"{story}b"][axis - 1]
                axial_load_ratio_top = frame.load_and_material.ppy[f"{story}t"][axis - 1]
                axial_load_scale = frame.load_and_material.axial_load_ratio_amplification_factor
                bottom_tag = self.get_id(10, floor_bottom, axis, 7)
                top_tag = self.get_id(10, floor_top, axis, 8)
                if story == 1:
                    inode_b = self.get_id(10, floor_bottom, axis, 0)
                else:
                    inode_b = self.get_id(11, floor_bottom, axis, 3)
                jnode_b = self.get_id(10, floor_bottom, axis, 1)
                inode_t = self.get_id(10, floor_top, axis, 2)
                jnode_t = self.get_id(11, floor_top, axis, 1)
                pinned = 1
                if floor_bottom == 1 and frame.connection_and_boundary.base_support == "Pinned":
                    pinned = 2
                write_temp_b.append(
                    f"ColumnHinge {bottom_tag} {inode_b} {jnode_b} $E {inertia_bottom:.2f} {d_b:.2f} {htw_b:.2f} {ry_b:.2f} {length:.2f} {unbraced_length:.2f} {yield_moment_bottom:.2f} {axial_load_ratio_bottom:.4f} {axial_load_scale} {pinned};"
                )
                write_temp_b_py.append(
                    f"ColumnHinge({bottom_tag}, {inode_b}, {jnode_b}, E, {inertia_bottom:.2f}, {d_b:.2f}, {htw_b:.2f}, {ry_b:.2f}, {length:.2f}, {unbraced_length:.2f}, {yield_moment_bottom:.2f}, {axial_load_ratio_bottom:.4f}, {axial_load_scale}, {pinned})"
                )
                write_temp_t.append(
                    f"ColumnHinge {top_tag} {inode_t} {jnode_t} $E {inertia_top:.2f} {d_t:.2f} {htw_t:.2f} {ry_t:.2f} {length:.2f} {unbraced_length:.2f} {yield_moment_top:.2f} {axial_load_ratio_top:.4f} {axial_load_scale} 1;"
                )
                write_temp_t_py.append(
                    f"ColumnHinge({top_tag}, {inode_t}, {jnode_t}, E, {inertia_top:.2f}, {d_t:.2f}, {htw_t:.2f}, {ry_t:.2f}, {length:.2f}, {unbraced_length:.2f}, {yield_moment_top:.2f}, {axial_load_ratio_top:.4f}, {axial_load_scale}, 1)"
                )
                self.zero_length(inode_b, jnode_b, element_id=bottom_tag)
                self.zero_length(inode_t, jnode_t, element_id=top_tag)
            self.write(*write_temp_b)
            self.writepy(*write_temp_b_py)
            self.write(*write_temp_t)
            self.writepy(*write_temp_t_py)
        self.write()
        self.writepy()

        # Rigid link
        self.write("# Rigid links")
        self.writepy("# Rigid links")
        for floor in range(2, frame.N + 2):
            bay = frame.bays + 1
            axis_left, axis_right = bay, bay + 1
            tag = self.get_id(10, floor, bay, 4)
            inode = self.get_id(11, floor, axis_left, 4)
            jnode = self.get_id(10, floor, axis_right, 0)
            self.write(f"element truss {tag} {inode} {jnode} $A_Stiff 99;")
            self.writepy(f'ops.element("truss", {tag}, {inode}, {jnode}, A_Stiff, 99)')
            self.ele(inode, jnode, element_id=tag)
        self.write()
        self.writepy()

        # Leaning column
        self.write("# Leaning column")
        self.writepy("# Leaning column")
        for story in range(1, frame.N + 1):
            floor_bottom, floor_top = story, story + 1
            axis = frame.axis + 1
            if story == 1:
                inode = self.get_id(10, floor_bottom, axis, 0)
            else:
                inode = self.get_id(10, floor_bottom, axis, 1)
            jnode = self.get_id(10, floor_top, axis, 2)
            tag = self.get_id(10, story, axis, 1)
            self.write(f"element elasticBeamColumn {tag} {inode} {jnode} $A_Stiff $E $I_Stiff 2;")
            self.writepy(
                f'ops.element("elasticBeamColumn", {tag}, {inode}, {jnode}, A_Stiff, E, I_Stiff, 2)'
            )
            self.ele(inode, jnode, element_id=tag)
        self.write()
        self.writepy()

        # Leaning column hinges
        self.write("# Leaning column hinges")
        self.writepy("# Leaning column hinges")
        for floor in range(2, frame.N + 2):
            axis = frame.axis + 1
            inode = self.get_id(10, floor, axis, 2)
            jnode = self.get_id(10, floor, axis, 0)
            knode = self.get_id(10, floor, axis, 1)
            primary_tag = self.get_id(10, floor, axis, 8)
            secondary_tag = self.get_id(10, floor, axis, 7)
            self.write(f"Spring_Rigid {primary_tag} {inode} {jnode};")
            self.writepy(f"Spring_Rigid({primary_tag}, {inode}, {jnode})")
            self.ele(inode, jnode, element_id=primary_tag)
            if floor != frame.N + 1:
                self.write(f"Spring_Zero {secondary_tag} {jnode} {knode};")
                self.writepy(f"Spring_Zero({secondary_tag}, {jnode}, {knode})")
                self.ele(jnode, knode, element_id=secondary_tag)
        self.write()
        self.writepy()

    def write_constraint(self):
        frame = self.frame
        s = " Constraints ".center(80, "-")
        self.write("# " + s)
        self.writepy("# " + s)
        self.write()
        self.writepy()

        # Support
        self.write("# Support")
        self.writepy("# Support")
        for axis in range(1, frame.axis + 2):
            tag = self.get_id(10, 1, axis, 0)
            if axis != frame.axis + 1:
                self.write(f"fix {tag} 1 1 1;")
                self.writepy(f"ops.fix({tag}, 1, 1, 1)")
            else:
                self.write(f"fix {tag} 1 1 0;")
                self.writepy(f"ops.fix({tag}, 1, 1, 0)")
        self.write()
        self.writepy()

        # soil constraint
        self.write("# Soil constraint")
        self.writepy("# Soil constraint")
        if not frame.connection_and_boundary.soil_constraint:
            self.write("# (No soil constraint)")
            self.writepy("# (No soil constraint)")
        for axis in range(1, frame.axis + 1):
            if (axis != 1) and (axis != frame.axis):
                continue
            for floor in frame.connection_and_boundary.soil_constraint:
                if frame.connection_and_boundary.panel_zone_deformation:
                    if axis == 1:
                        tag = self.get_id(11, floor, axis, 2)
                    else:
                        tag = self.get_id(11, floor, axis, 4)
                else:
                    tag = self.get_id(11, floor, axis, 0)
                self.write(f"fix {tag} 1 0 0;")
                self.writepy(f"ops.fix({tag}, 1, 0, 0)")
        self.write()
        self.writepy()

        # Rigig diaphragm
        self.write("# Rigid diaphragm")
        self.writepy("# Rigid diaphragm")
        if not frame.connection_and_boundary.rigid_diaphragm:
            self.write("# (Rigid diaphragm was not considered)")
            self.writepy("# (Rigid diaphragm was not considered)")
        master_axis = int((frame.axis + 1) / 2)
        slave_axis = []
        for axis in range(1, frame.axis + 1):
            if axis != master_axis:
                slave_axis.append(axis)
        self.control_nodes = []
        for floor in range(2, frame.N + 2):
            write_temp = []
            write_temp_py = []
            for axis in slave_axis:
                if frame.connection_and_boundary.panel_zone_deformation:
                    inode = self.get_id(11, floor, master_axis, 4)
                    jnode = self.get_id(11, floor, axis, 4)
                else:
                    inode = self.get_id(11, floor, master_axis, 0)
                    jnode = self.get_id(11, floor, axis, 0)
                write_temp.append(f"equalDOF {inode} {jnode} 1;")
                write_temp_py.append(f"ops.equalDOF({inode}, {jnode}, 1)")
            self.control_nodes.append(inode)
            if frame.connection_and_boundary.rigid_diaphragm:
                self.write(*write_temp)
                self.writepy(*write_temp_py)
        self.write()
        self.writepy()
        self.master_axis = master_axis  # control axes

    def write_recorders(self):
        frame = self.frame
        s = " Recorders ".center(80, "-")
        self.write("# " + s)
        self.writepy("# " + s)
        self.write()
        self.writepy()
        self.write("# Time")
        self.writepy("# Time")
        self.write(
            "recorder Node -file $MainFolder/$SubFolder/Time.out -time -node 10010100 -dof 1 disp;"
        )
        self.writepy(
            'ops.recorder("Node", "-file", str(MainFolder/SubFolder/"Time.out"), "-time", "-node", 10010100, "-dof", 1, "disp")'
        )
        self.write()
        self.writepy()
        self.write("# Support reactions")
        self.writepy("# Support reactions")
        for axis in range(1, frame.axis + 2):
            tag = self.get_id(10, 1, axis, 0)
            if frame.recorders["Reactions"]:
                self.write(
                    f"recorder Node -file $MainFolder/$SubFolder/Support{axis}.out -node {tag} -dof 1 2 3 reaction;"
                )
                self.writepy(
                    f'ops.recorder("Node", "-file", str(MainFolder/SubFolder/"Support{axis}.out"), "-node", {tag}, "-dof", 1, 2, 3, "reaction")'
                )
                self.add_recorder()
        self.write()
        self.writepy()
        self.write("# Story drift ratio")
        self.writepy("# Story drift ratio")
        for story in range(1, frame.N + 1):
            if story == 1:
                inode = 10010100
            else:
                inode = self.control_nodes[story - 2]
            jnode = self.control_nodes[story - 1]
            if frame.recorders["Drift"]:
                self.write(
                    f"recorder Drift -file $MainFolder/$SubFolder/SDR{story}.out -iNode {inode} -jNode {jnode} -dof 1 -perpDirn 2;"
                )
                self.writepy(
                    f'# ops.recorder("Drift", "-file", str(MainFolder/SubFolder/"SDR{story}.out"), "-iNode", {inode}, "-jNode", {jnode}, "-dof", 1, "-perpDirn", 2)'
                )
                self.add_recorder()
        if frame.recorders["Drift"]:
            self.write(
                f"recorder Drift -file $MainFolder/$SubFolder/SDR_Roof.out -iNode 10010100 -jNode {jnode} -dof 1 -perpDirn 2;"
            )
            self.writepy(
                f'# ops.recorder("Drift", "-file", str(MainFolder/SubFolder/"SDR_Roof.out"), "-iNode", 10010100, "-jNode", {jnode}, "-dof", 1, "-perpDirn", 2)'
            )
            self.add_recorder()
        self.write()
        self.writepy()
        self.write("# Floor acceleration")
        self.writepy("# Floor acceleration")
        for floor in range(1, frame.N + 2):
            if floor == 1:
                inode = 10010100
            else:
                inode = self.control_nodes[floor - 2]
            if frame.recorders["FloorAccel"]:
                self.write(
                    f"recorder Node -file $MainFolder/$SubFolder/RFA{floor}.out -node {inode} -dof 1 accel;"
                )
                self.writepy(
                    f'ops.recorder("Node", "-file", str(MainFolder/SubFolder/"RFA{floor}.out"), "-node", {inode}, "-dof", 1, "accel")'
                )
                self.add_recorder()
        self.write()
        self.write("# Floor velocity")
        for floor in range(1, frame.N + 2):
            if floor == 1:
                inode = 10010100
            else:
                inode = self.control_nodes[floor - 2]
            if frame.recorders["FloorVel"]:
                self.write(
                    f"recorder Node -file $MainFolder/$SubFolder/RFV{floor}.out -node {inode} -dof 1 vel;"
                )
                self.writepy(
                    f'ops.recorder("Node", "-file", str(MainFolder/SubFolder/"RFV{floor}.out"), "-node", {inode}, "-dof", 1, "vel")'
                )
                self.add_recorder()
        self.write()
        self.writepy()
        self.write("# Floor displacement")
        self.writepy("# Floor displacement")
        for floor in range(1, frame.N + 2):
            if floor == 1:
                inode = 10010100
            else:
                inode = self.control_nodes[floor - 2]
            if frame.recorders["FloorDisp"]:
                self.write(
                    f"recorder Node -file $MainFolder/$SubFolder/Disp{floor}.out -node {inode} -dof 1 disp;"
                )
                self.writepy(
                    f'ops.recorder("Node", "-file", str(MainFolder/SubFolder/"Disp{floor}.out"), "-node", {inode}, "-dof", 1, "disp")'
                )
                self.add_recorder()
        self.write()
        self.writepy()
        self.write("# Shear forces")
        self.writepy("# Shear forces")
        for story in range(1, frame.N + 1):
            write_temp = []
            write_temp_py = []
            for axis in range(1, frame.axis + 1):
                tag = self.get_id(10, story, axis, 1)
                if tag not in self.eles_Id:
                    tag = self.get_id(10, story, axis, 2)
                if frame.recorders["ColumnForce"]:
                    write_temp.append(
                        f"recorder Element -file $MainFolder/$SubFolder/Shear{story}_{axis}.out -ele {tag} force;"
                    )
                    write_temp_py.append(
                        f'ops.recorder("Element", "-file", str(MainFolder/SubFolder/"Shear{story}_{axis}.out"), "-ele", {tag}, "force")'
                    )
                    self.add_recorder()
            self.write(*write_temp)
            self.writepy(*write_temp_py)
        self.write()
        self.writepy()
        self.write("# Column springs")
        self.writepy("# Column springs")
        for story in range(1, frame.N + 1):
            write_temp_b, write_temp_t = [], []
            write_temp_b_py, write_temp_t_py = [], []
            floor_bottom, floor_top = story, story + 1
            for axis in range(1, frame.axis + 1):
                bottom_tag = self.get_id(10, floor_bottom, axis, 7)
                top_tag = self.get_id(10, floor_top, axis, 8)
                if frame.recorders["ColumnHinge"]:
                    write_temp_b.append(
                        f"recorder Element -file $MainFolder/$SubFolder/ColSpring{floor_bottom}_{axis}T.out -ele {bottom_tag} material 3 stressStrain;"
                    )
                    write_temp_b_py.append(
                        f'ops.recorder("Element", "-file", str(MainFolder/SubFolder/"ColSpring{floor_bottom}_{axis}T.out"), "-ele", {bottom_tag}, "material", 3, "stressStrain")'
                    )
                    write_temp_t.append(
                        f"recorder Element -file $MainFolder/$SubFolder/ColSpring{floor_top}_{axis}B.out -ele {top_tag} material 3 stressStrain;"
                    )
                    write_temp_t_py.append(
                        f'ops.recorder("Element", "-file", str(MainFolder/SubFolder/"ColSpring{floor_top}_{axis}B.out"), "-ele", {top_tag}, "material", 3, "stressStrain")'
                    )
                    self.add_recorder()
                    self.add_recorder()
            self.write(*write_temp_b)
            self.writepy(*write_temp_b_py)
            self.write(*write_temp_t)
            self.writepy(*write_temp_t_py)
        self.write()
        self.writepy()
        self.write("# Beam springs")
        self.writepy("# Beam springs")
        for floor in range(2, frame.N + 2):
            write_temp = []
            write_temp_py = []
            for bay in range(1, frame.bays + 1):
                axis_left, axis_right = bay, bay + 1
                left_tag = self.get_id(10, floor, axis_left, 9)
                right_tag = self.get_id(10, floor, axis_right, 10)
                if frame.recorders["BeamHinge"]:
                    write_temp.append(
                        f"recorder Element -file $MainFolder/$SubFolder/BeamSpring{floor}_{axis_left}R.out -ele {left_tag} material 3 stressStrain;"
                    )
                    write_temp_py.append(
                        f'ops.recorder("Element", "-file", str(MainFolder/SubFolder/"BeamSpring{floor}_{axis_left}R.out"), "-ele", {left_tag}, "material", 3, "stressStrain")'
                    )
                    write_temp.append(
                        f"recorder Element -file $MainFolder/$SubFolder/BeamSpring{floor}_{axis_right}L.out -ele {right_tag} material 3 stressStrain;"
                    )
                    write_temp_py.append(
                        f'ops.recorder("Element", "-file", str(MainFolder/SubFolder/"BeamSpring{floor}_{axis_right}L.out"), "-ele", {right_tag}, "material", 3, "stressStrain")'
                    )
                    self.add_recorder()
                    self.add_recorder()
            self.write(*write_temp)
            self.writepy(*write_temp_py)
        self.write()
        self.writepy()
        self.write("# Panel zone springs (if any)")
        self.writepy("# Panel zone springs (if any)")
        for floor in range(2, frame.N + 2):
            if not frame.connection_and_boundary.panel_zone_deformation:
                break
            write_temp = []
            write_temp_py = []
            for axis in range(1, frame.axis + 1):
                tag = self.get_id(11, floor, axis, 0)
                if frame.recorders["PanelZone"]:
                    write_temp.append(
                        f"recorder Element -file $MainFolder/$SubFolder/PZ{floor}_{axis}.out -ele {tag} material 1 stressStrain;"
                    )
                    write_temp_py.append(
                        f'ops.recorder("Element", "-file", str(MainFolder/SubFolder/"PZ{floor}_{axis}.out"), "-ele", {tag}, "material", 1, "stressStrain")'
                    )
                    self.add_recorder()
            self.write(*write_temp)
            self.writepy(*write_temp_py)
        self.write()
        self.writepy()
        self.write("# MPCO recorder")
        self.write("if {$MPCO == 1} {")
        self.write(
            "    recorder mpco $MainFolder/$SubFolder/result.mpco -N displacement acceleration modesOfVibration -E material.stress material.strain;"
        )
        self.write("}")
        self.write()

    def write_mass(self):
        frame = self.frame
        s = " Mass ".center(80, "-")
        self.write("# " + s)
        self.writepy("# " + s)
        self.write()
        self.writepy()
        self.write("# Moment frame mass")
        self.writepy("# Moment frame mass")
        self.write("set g 9810.0;")
        self.writepy("g = 9810.0")
        for floor in range(2, frame.N + 2):
            write_temp = []
            write_temp_py = []
            for axis in range(1, frame.axis + 1):
                if frame.connection_and_boundary.panel_zone_deformation:
                    tag = self.get_id(11, floor, axis, 4)
                else:
                    tag = self.get_id(11, floor, axis, 0)
                mass = frame.load_and_material.moment_frame_node_mass[floor][axis - 1]
                mass_text = _plain_number(mass)
                write_temp.append(f"mass {tag} {mass_text} 1.e-9 1.e-9;")
                write_temp_py.append(f"ops.mass({tag}, {mass_text}, 1.e-9, 1.e-9)")
            self.write(*write_temp)
            self.writepy(*write_temp_py)
        self.write()
        self.writepy()
        self.write("# Leaning column mass")
        self.writepy("# Leaning column mass")
        for floor in range(2, frame.N + 2):
            axis = frame.axis + 1
            tag = self.get_id(10, floor, axis, 0)
            mass = frame.load_and_material.leaning_column_node_mass[floor]
            mass_text = _plain_number(mass)
            self.write(f"mass {tag} {mass_text} 1.e-9 1.e-9;")
            self.writepy(f"ops.mass({tag}, {mass_text}, 1.e-9, 1.e-9)")
        self.write()
        self.writepy()
        self.write()
        self.writepy()

    def write_user_comments_tcl(self):
        uesr_commands = self.frame.user_comment.additional_commands_tcl
        if not uesr_commands:
            return
        s = " User comments ".center(80, "-")
        self.write("# " + s)
        self.write()
        for command in uesr_commands:
            type_ = list(command.keys())[0]
            if type_ == "node":
                paras = command["node"].strip(";").split(" ")
                tag, x, y = int(paras[1]), float(paras[2]), float(paras[3])
                if tag in self.nodes_Id:
                    print(f"User command warning: node {tag} was already existed")
                self.node(x, y, node_id=tag, c="orange", check=False)
                self.write(command["node"])
            elif type_ == "mat":
                self.write(command["mat"])
            elif type_ == "ele":
                paras = command["ele"].strip(";").split(" ")
                tag, inode, jnode = int(paras[2]), int(paras[3]), int(paras[4])
                if tag in self.eles_Id:
                    print(f"User command warning: element {tag} was already existed")
                self.ele(inode, jnode, element_id=tag, c="orange", check=False)
                self.write(command["ele"])
            elif type_ == "any":
                self.write(command["any"])
        self.write()

    def write_user_comments_py(self):
        uesr_commands = self.frame.user_comment.additional_commands_py
        if not uesr_commands:
            return
        s = " User comments ".center(80, "-")
        self.writepy("# " + s)
        self.writepy()
        for command in uesr_commands:
            type_ = list(command.keys())[0]
            if type_ == "node":
                paras = command["node"].strip(")").strip("ops.node(").split(",")
                tag, x, y = int(paras[0]), float(paras[1]), float(paras[2])
                self.node(x, y, node_id=tag, c="orange", check=False)
                self.writepy(command["node"])
            elif type_ == "mat":
                self.writepy(command["mat"])
            elif type_ == "ele":
                paras = command["ele"].strip(")").split(",")
                tag, inode, jnode = int(paras[1]), int(paras[2]), int(paras[3])
                self.ele(inode, jnode, element_id=tag, c="orange", check=False)
                self.writepy(command["ele"])
            elif type_ == "any":
                self.writepy(command["any"])
        self.writepy()

    def write_eigen(self):
        frame = self.frame
        s = " Eigen analysis ".center(80, "-")
        self.write("# " + s)
        self.writepy("# " + s)
        self.write()
        self.writepy()
        self.write("set pi [expr 2.0*asin(1.0)];")
        self.write(f"set nEigen {frame.N}")
        self.writepy(f"nEigen = {frame.N}")
        self.write("set lambdaN [eigen [expr $nEigen]];")
        self.writepy("lambdaN = ops.eigen(nEigen)")
        for story in range(1, frame.N + 1):
            self.write(f"set lambda{story} [lindex $lambdaN {story - 1}];")
            self.writepy(f"lambda{story} = lambdaN[{story - 1}]")
        for story in range(1, frame.N + 1):
            self.write(f"set w{story} [expr pow($lambda{story}, 0.5)];")
            self.writepy(f"w{story} = pow(lambda{story}, 0.5)")
        for story in range(1, frame.N + 1):
            self.write(f"set T{story} [expr round(2.0*$pi/$w{story} *1000.)/1000.];")
            self.writepy(f"T{story} = round(2.0*pi/w{story}, 3)")
        for story in range(1, frame.N + 1):
            self.write(f'puts "T{story} = $T{story} s";')
            self.writepy(f'print(f"T{story} = {{T{story}}} s")')
            if story == 3:
                break
        self.write()
        self.writepy()

        self.write("set mode [list]")
        self.writepy("mode = []")
        self.write("for {set i 1} {$i <= $NStory} {incr i} {")
        self.writepy("for i in range(1, NStory + 1):")
        for story in range(1, frame.N + 1):
            self.write(
                f"    lappend mode [expr [nodeEigenvector {self.control_nodes[story - 1]} $i 1]]"
            )
            self.writepy(
                f"    mode.append(ops.nodeEigenvector({self.control_nodes[story - 1]}, i, 1))"
            )
        self.write('    set file_mode [open "$MainFolder/$SubFolder/mode$i.out" w]')
        self.write("    foreach val $mode {puts $file_mode $val}")
        self.write("    close $file_mode")
        self.writepy('    np.savetxt(MainFolder/SubFolder/f"mode{i}.out", mode)')
        self.write("    if {$i == 1} {set mode_list $mode}")
        self.writepy("    if i == 1:")
        self.writepy("        mode_list = mode.copy()")
        self.write("    set mode [list]")
        self.writepy("    mode = []")
        self.write("};")
        self.write()
        self.write('set file_T [open "$MainFolder/$SubFolder/Period.out" w];')
        self.writepy('with open(MainFolder/SubFolder/"Period.out", "w") as f:')
        for story in range(1, frame.N + 1):
            self.write(f"puts $file_T $T{story};")
            self.writepy(f'    f.write(f"{{T{story}}}\\n")')
        self.write("close $file_T;")
        self.write()
        self.write()
        self.writepy()
        self.writepy()

    def write_gravity(self):
        frame = self.frame
        s = " Static gravity analysis ".center(80, "-")
        self.write("# " + s)
        self.writepy("# " + s)
        self.write()
        self.writepy()
        self.write("pattern Plain 100 Linear {")
        self.writepy('ops.timeSeries("Linear", 100)')
        self.writepy('ops.pattern("Plain", 100, 100)')
        self.write()
        self.writepy()
        self.write("    # Moment frame loads")
        self.writepy("# Moment frame loads")
        for floor in range(2, frame.N + 2):
            write_temp = []
            write_temp_py = []
            for axis in range(1, frame.axis + 1):
                load = -frame.load_and_material.moment_frame_node_vertical_load[floor][axis - 1]
                tag = self.get_id(11, floor, axis, 1)
                load_text = _plain_number(load)
                write_temp.append(f"    load {tag} 0. {load_text} 0.;")
                write_temp_py.append(f"ops.load({tag}, 0., {load_text}, 0.)")
            self.write(*write_temp)
            self.writepy(*write_temp_py)
        self.write()
        self.writepy()
        self.write("    # gravity frame loads")
        self.writepy("# gravity frame loads")
        for floor in range(2, frame.N + 2):
            load = -frame.load_and_material.leaning_column_node_vertical_load[floor]
            axis = frame.axis + 1
            tag = self.get_id(10, floor, axis, 0)
            load_text = _plain_number(load)
            self.write(f"    load {tag} 0. {load_text} 0.;")
            self.writepy(f"ops.load({tag}, 0., {load_text}, 0.)")
        self.write()
        self.writepy()
        self.write("}")
        self.write()
        self.write("wipeAnalysis")
        self.writepy("ops.wipeAnalysis()")
        self.write("constraints Transformation;")
        self.writepy('ops.constraints("Transformation")')
        self.write("numberer RCM;")
        self.writepy('ops.numberer("RCM")')
        self.write("system BandGeneral;")
        self.writepy('ops.system("BandGeneral")')
        self.write("test NormDispIncr 1.0e-5 60;")
        self.writepy('ops.test("NormDispIncr", 1.0e-5, 60)')
        self.write("algorithm Newton;")
        self.writepy('ops.algorithm("Newton")')
        self.write("integrator LoadControl 0.1;")
        self.writepy('ops.integrator("LoadControl", 0.1)')
        self.write("analysis Static;")
        self.writepy('ops.analysis("Static")')
        self.write("set gravityStatus [analyze 10];")
        self.writepy("gravity_status = ops.analyze(10)")
        self.write("if {$gravityStatus != 0} {")
        self.writepy("if gravity_status != 0:")
        self.write(
            '    puts "WARNING: Static gravity analysis did not converge '
            "(OpenSees code: $gravityStatus, committed load factor: [getTime]). "
            'Continuing with the last committed state.";'
        )
        self.writepy(
            '    print(f"WARNING: Static gravity analysis did not converge '
            "(OpenSees code: {gravity_status}, committed load factor: {ops.getTime()}). "
            'Continuing with the last committed state.")'
        )
        self.write("}")
        self.write("loadConst -time 0.0;")
        self.writepy('ops.loadConst("-time", 0.0)')
        self.write()
        self.write()
        self.writepy()
        self.writepy()

    def write_dynamic_analysis(self):
        frame = self.frame
        s = " Time history analysis ".center(80, "-")
        self.write("# " + s)
        self.writepy("# " + s)
        self.write()
        self.writepy()
        self.write(
            "if {$ShowAnimation == 1} {DisplayModel3D DeformedShape 5.00 100 100 1600 1000};"
        )
        moment_frame_nodes_py = ", ".join([str(i) for i in self.control_nodes])
        moment_frame_nodes_tcl = " ".join([str(i) for i in self.control_nodes])
        self.write(f"set MF_FloorNodes [list {moment_frame_nodes_tcl}];")
        self.writepy(f"MF_FloorNodes = [{moment_frame_nodes_py}]")
        self.write()
        self.writepy()
        self.write('if {$analysis_type == "TH"} {')
        self.writepy('if analysis_type == "TH":')
        self.write("")
        self.write("    # Rayleigh damping")
        self.writepy("    # Rayleigh damping")
        self.write("    set zeta 0.02;")
        self.writepy("    zeta = 0.02")
        self.write("    set a0 [expr $zeta*2.0*$w1*$w3/($w1 + $w3)];")
        self.writepy("    a0 = zeta * 2.0 * w1 * w3 / (w1 + w3)")
        self.write("    set a1 [expr $zeta*2.0/($w1 + $w3)];")
        self.writepy("    a1 = zeta * 2.0 / (w1 + w3)")
        self.write("    set a1_mod [expr $a1*(1.0+$n)/$n];")
        self.writepy("    a1_mod = a1 * (1.0 + n) / n")
        beam_ids = []
        for floor in range(2, frame.N + 2):
            for bay in range(1, frame.bays + 1):
                tag = self.get_id(10, floor, bay, 4)
                if tag in self.eles_Id:
                    beam_ids.append(str(tag))
                else:
                    left_tag = self.get_id(10, floor, bay, 11)
                    right_tag = self.get_id(10, floor, bay, 12)
                    beam_ids.append(str(left_tag))
                    beam_ids.append(str(right_tag))
        beam_ids_py = ", ".join(beam_ids)
        beam_ids = " ".join(beam_ids)
        self.write(f"    set beam_Ids [list {beam_ids}];")
        self.writepy(f"    beam_Ids = [{beam_ids_py}]")
        column_ids = []
        for story in range(1, frame.N + 1):
            for axis in range(1, frame.axis + 1):
                tag = self.get_id(10, story, axis, 1)
                if tag in self.eles_Id:
                    column_ids.append(str(tag))
                else:
                    bottom_tag = self.get_id(10, story, axis, 2)
                    top_tag = self.get_id(10, story, axis, 3)
                    column_ids.append(str(bottom_tag))
                    column_ids.append(str(top_tag))
        column_ids_py = ", ".join(column_ids)
        column_ids = " ".join(column_ids)
        self.write(f"    set column_Ids [list {column_ids}];")
        self.writepy(f"    column_Ids = [{column_ids_py}]")
        mass_ids = []
        for floor in range(2, frame.N + 2):
            for axis in range(1, frame.axis + 1):
                if frame.connection_and_boundary.panel_zone_deformation:
                    tag = self.get_id(11, floor, axis, 4)
                else:
                    tag = self.get_id(11, floor, axis, 0)
                mass_ids.append(str(tag))
        for floor in range(2, frame.N + 2):
            tag = self.get_id(10, floor, frame.axis + 1, 0)
            mass_ids.append(str(tag))
        mass_ids_py = ", ".join(mass_ids)
        mass_ids = " ".join(mass_ids)
        self.write(f"    set mass_Ids [list {mass_ids}];")
        self.writepy(f"    mass_Ids = [{mass_ids_py}]")
        self.write("    # region 1 -ele {*}$beam_Ids -rayleigh 0.0 0.0 $a1_mod 0.0;")
        self.writepy('    # ops.region(1, "-ele", *beam_Ids, "-rayleigh", 0.0, 0.0, a1_mod, 0.0)')
        self.write("    # region 2 -ele {*}$column_Ids -rayleigh 0.0 0.0 $a1_mod 0.0;")
        self.writepy('    # ops.region(2, "-ele", *column_Ids, "-rayleigh", 0.0, 0.0, a1_mod, 0.0)')
        self.write("    # region 3 -ele {*}$mass_Ids -rayleigh $a0 0.0 0.0 0.0;")
        self.writepy('    # ops.region(3, "-ele", *mass_Ids, "-rayleigh", a0, 0.0, 0.0, 0.0)')
        self.write("    rayleigh $a0 0.0 $a1 0.0;")
        self.writepy("    ops.rayleigh(a0, 0.0, a1, 0.0)")
        self.write("")
        self.writepy("    ")
        self.write("    # Ground motion acceleration file input")
        self.writepy("    # Ground motion acceleration file input")
        self.write("    timeSeries Path 200 -dt $GMdt -filePath $GMFile -factor [expr $EqSF * $g];")
        self.writepy(
            '    ops.timeSeries("Path", 200, "-dt", GMdt, "-filePath", GMFile, "-factor", EqSF * g)'
        )
        self.write(
            f"    recorder Node -file $MainFolder/$SubFolder/groundmotion.out -timeSeries 200 -node {self.get_id(10, 1, 1, 0)} -dof 1 accel;"
        )
        self.writepy(
            f'    ops.recorder("Node", "-file", str(MainFolder/SubFolder/"groundmotion.out"), "-timeSeries", 200, "-node", {self.get_id(10, 1, 1, 0)}, "-dof", 1, "accel")'
        )
        self.write("    pattern UniformExcitation 200 1 -accel 200;")
        self.writepy('    ops.pattern("UniformExcitation", 200, 1, "-accel", 200)')
        self.write("    set totalTime [expr $GMduration + $FVduration];")
        self.writepy("    totalTime = GMduration + FVduration")
        self.write("    set CollapseDrift 0.1;  # $$$")
        self.write("    set MaxAnalysisDrift 0.5;")
        self.writepy("    MaxAnalysisDrift = 0.5")
        self.write(
            "    set result [TimeHistorySolver $GMdt $totalTime $story_heights $MF_FloorNodes $CollapseDrift $MaxAnalysisDrift $GMname $maxRunTime $temp];"
        )
        self.write("    set status [lindex $result 0];")
        self.write("    set controlled_time [lindex $result 1];")
        self.write('    puts "Running status: $status";')
        self.write('    puts "Controlled time: $controlled_time";')
        self.writepy(
            "    result = TimeHistorySolver(GMdt, totalTime, story_height, MF_FloorNodes, CollapseDrift, MaxAnalysisDrift, GMname, maxRunTime, ShowAnimation)"
        )
        self.writepy('    print(f"Running status: {result[0]}")')
        self.writepy('    print(f"Control time: {result[1]}")')
        self.writepy('    print(f"Collapse: {bool(result[2])}")')
        self.writepy("    for i in range(NStory):")
        self.writepy("        SDR = result[3][:, i]")
        self.writepy('        np.savetxt(MainFolder/SubFolder/f"SDR{i+1}.out", SDR, fmt="%.6f")')
        self.writepy('    np.savetxt(MainFolder/SubFolder/f"SDR_Roof.out", result[4], fmt="%.6f")')
        self.writepy("")
        self.write("")

    def write_pushover_analysis(self):
        frame = self.frame
        s = " Pushover analysis ".center(80, "-")
        self.write("# " + s)
        self.writepy("# " + s)
        self.write()
        self.writepy()
        self.write('} elseif {$analysis_type == "PO"} {')
        self.writepy('elif analysis_type == "PO":')
        self.write()
        for floor in range(2, frame.N + 2):
            mass = sum(frame.load_and_material.moment_frame_node_mass[floor])
            mass += frame.load_and_material.leaning_column_node_mass[floor]
            mass_text = _plain_number(mass)
            self.write(f"    set m{floor} {mass_text};")
            self.writepy(f"    m{floor} = {mass_text}")
        self.write()
        self.writepy()
        for floor in range(2, frame.N + 2):
            self.write(f"    set F{floor} [expr $m{floor} * [lindex $mode_list {floor - 2}]];")
            self.writepy(f"    F{floor} = m{floor} * mode_list[{floor - 2}]")
        self.write("    set file_pattern [open $MainFolder/$SubFolder/Pattern.out w]")
        for floor in range(2, frame.N + 2):
            self.write(f"    puts $file_pattern $F{floor}")
        self.write("    close $file_pattern")
        force_values = ", ".join([f"F{floor}" for floor in range(2, frame.N + 2)])
        self.writepy(f"    F_ls = [{force_values}]")
        self.writepy('    np.savetxt(MainFolder/SubFolder/"Pattern.out", F_ls, fmt="%.6f")')
        self.write("    pattern Plain 222 Linear {")
        self.writepy('    ops.timeSeries("Linear", 222)')
        self.writepy('    ops.pattern("Plain", 222, 222)')
        for floor in range(2, frame.N + 2):
            tag = self.control_nodes[floor - 2]
            self.write(f"        load {tag} $F{floor} 0.0 0.0;")
            self.writepy(f"    ops.load({tag}, F{floor}, 0.0, 0.0)")
        self.write("    };")
        self.write(f"    set CtrlNode {self.control_nodes[-1]};")
        self.write("    set maxRoofDrift 0.1;  # $$$")
        self.write(f"    set Dmax [expr $maxRoofDrift * $Floor{frame.N + 1}];")
        self.writepy(f"    Dmax = maxRoofDrift * Floor{frame.N + 1}")
        self.write("    set Dincr 0.5;")
        self.writepy("    Dincr = 0.5")
        self.write("    set result [PushoverAnalysis $CtrlNode $Dmax $Dincr $maxRunTime];")
        self.writepy(
            "    result = PushoverAnalysis(MF_FloorNodes, story_height, Dmax, Dincr, maxRunTime, ShowAnimation)"
        )
        self.write("    set status [lindex $result 0];")
        self.writepy("    status = result[0]")
        self.write("    set roofDisp [lindex $result 1];")
        self.writepy("    roofDisp = result[1]")
        self.write('    puts "Running status: $status";')
        self.writepy('    print(f"Running status: {status}")')
        self.write('    puts "Roof displacement: $roofDisp";')
        self.writepy('    print(f"Roof displacement: {roofDisp}")')
        self.write('    puts "Roof drift ratio: [expr $roofDisp / $HBuilding]";')
        self.writepy('    print(f"Roof drift ratio: {roofDisp / HBuilding}")')
        self.writepy("    for i in range(NStory):")
        self.writepy("        SDR = result[2][:, i]")
        self.writepy('        np.savetxt(MainFolder/SubFolder/f"SDR{i+1}.out", SDR, fmt="%.6f")')
        self.writepy('    np.savetxt(MainFolder/SubFolder/f"SDR_Roof.out", result[3], fmt="%.6f")')
        self.write()
        self.writepy()

    def write_cyclic_pushover(self):
        frame = self.frame
        s = " Cyclic pushover ".center(80, "-")
        self.write("# " + s)
        self.writepy("# " + s)
        self.write()
        self.writepy()
        self.write('} elseif {$analysis_type == "CP"} {')
        self.writepy('elif analysis_type == "CP":')
        self.write()
        self.writepy()
        self.write("    set RDR_path [list 0 0.02 -0.02 0];  # $$$")
        self.write()
        for floor in range(2, frame.N + 2):
            mass = sum(frame.load_and_material.moment_frame_node_mass[floor])
            mass += frame.load_and_material.leaning_column_node_mass[floor]
            mass_text = _plain_number(mass)
            self.write(f"    set m{floor} {mass_text};")
            self.writepy(f"    m{floor} = {mass_text}")
        self.write()
        self.writepy()
        for floor in range(2, frame.N + 2):
            self.write(f"    set F{floor} [expr $m{floor} * [lindex $mode_list {floor - 2}]];")
            self.writepy(f"    F{floor} = m{floor} * mode_list[{floor - 2}]")
        self.write("    set file_pattern [open $MainFolder/$SubFolder/Pattern.out w]")
        for floor in range(2, frame.N + 2):
            self.write(f"    puts $file_pattern $F{floor}")
        self.write("    close $file_pattern")
        force_values = ", ".join([f"F{floor}" for floor in range(2, frame.N + 2)])
        self.writepy(f"    F_ls = [{force_values}]")
        self.writepy('    np.savetxt(MainFolder/SubFolder/"Pattern.out", F_ls, fmt="%.6f")')
        self.write("    pattern Plain 222 Linear {")
        self.writepy('    ops.timeSeries("Linear", 222)')
        self.writepy('    ops.pattern("Plain", 222, 222)')
        for floor in range(2, frame.N + 2):
            tag = self.control_nodes[floor - 2]
            self.write(f"        load {tag} $F{floor} 0.0 0.0;")
            self.writepy(f"    ops.load({tag}, F{floor}, 0.0, 0.0)")
        self.write("    };")
        self.write(f"    set CtrlNode {self.control_nodes[-1]};")
        self.writepy(f"    CtrlNode = {self.control_nodes[-1]}")
        self.write("    set Dincr 0.5;")
        self.writepy("    Dincr = 0.5")
        self.write(
            "    set result [CyclicPushover $CtrlNode $RDR_path $HBuilding $Dincr $maxRunTime];"
        )
        self.writepy(
            "    result = CyclicPushover(CtrlNode, RDR_path, HBuilding, Dincr, maxRunTime, ShowAnimation)"
        )
        self.write("    set status [lindex $result 0];")
        self.writepy("    status = result[0]")
        self.write('    puts "Running status: $status";')
        self.writepy('    print("Running status", status)')
        self.write()
        self.writepy()
        self.writepy('else:\n        assert False, "Should not reach here"')
        self.writepy()
        self.writepy('np.savetxt(MainFolder/SubFolder/"Status.dat", [status], fmt="%d")')
        self.writepy("return result")
        self.write("}")
        self.write()
        self.write('set file_status [open "$MainFolder/$SubFolder/Status.dat" w]')
        self.write("puts $file_status $status")
        self.write("close $file_status")
        self.write("wipe all")
        self.write()

    def write_info(self):
        frame = self.frame
        self.write()
        self.writepy()
        s = " Building information ".center(80, "-")
        self.write("# " + s)
        self.writepy("# " + s, start="")
        self.write("#")
        self.writepy("#", start="")
        text = frame.building_info
        lines = text.split("\n")
        for line in lines:
            self.write("# " + line)
            self.writepy("# " + line, start="")
        self.write()
        self.write()
        self.writepy()
        self.writepy()

    def add_panel_zone(self, floor, axis, x, y, d_col, d_beam, type_, position):
        """Construct panel zone model"""
        # node ID
        node_c = 11000000 + floor * 10000 + axis * 100  # 11FFAA01
        node_b = node_c + 1  # 11FFAA01
        node_l = node_c + 2  # 11FFAA02
        node_t = node_c + 3  # 11FFAA03
        node_r = node_c + 4  # 11FFAA04
        node_bl = node_c + 5  # 11FFAA05
        node_lb = node_c + 6  # 11FFAA06
        node_lt = node_c + 7  # 11FFAA07
        node_tl = node_c + 8  # 11FFAA08
        node_tr = node_c + 9  # 11FFAA09
        node_rt = node_c + 10  # 11FFAA10
        node_rb = node_c + 11  # 11FFAA11
        node_br = node_c + 12  # 11FFAA12
        # Construct nodes
        c = "green"
        if type_ == 1:
            self.node(x, y - 0.5 * d_beam, c, node_id=node_b)
            self.node(x + 0.5 * d_col, y, c, node_id=node_r)
            self.node(x, y + 0.5 * d_beam, c, node_id=node_t)
            self.node(x - 0.5 * d_col, y, c, node_id=node_l)
        elif type_ == 2:
            self.node(x, y - 0.5 * d_beam, c, node_id=node_b)
            self.node(x + 0.5 * d_col, y, c, node_id=node_r)
            if position != "L" and position != "LT":
                self.node(x - 0.5 * d_col, y, c, node_id=node_l)
            if position != "T" and position != "LT" and position != "RT":
                self.node(x, y + 0.5 * d_beam, c, node_id=node_t)
        if type_ == 1:
            self.node(x - 0.5 * d_col, y - 0.5 * d_beam, c, node_bl)
            self.node(x - 0.5 * d_col, y - 0.5 * d_beam, c, node_lb)
            self.node(x - 0.5 * d_col, y + 0.5 * d_beam, c, node_lt)
            self.node(x - 0.5 * d_col, y + 0.5 * d_beam, c, node_tl)
            self.node(x + 0.5 * d_col, y + 0.5 * d_beam, "red", node_tr)
            self.node(x + 0.5 * d_col, y + 0.5 * d_beam, "red", node_rt)
            self.node(x + 0.5 * d_col, y - 0.5 * d_beam, c, node_rb)
            self.node(x + 0.5 * d_col, y - 0.5 * d_beam, c, node_br)
        elif type_ == 2:
            self.node(x, y, c, node_c)
        # Rigid elements ID
        element_b = 11000000 + floor * 10000 + axis * 100 + 1
        element_l = element_b + 1
        element_t = element_b + 2
        element_r = element_b + 3
        element_bl = 11000000 + floor * 10000 + axis * 100 + 1
        element_lb = element_bl + 1
        element_lt = element_bl + 2
        element_tl = element_bl + 3
        element_tr = element_bl + 4
        element_rt = element_bl + 5
        element_rb = element_bl + 6
        element_br = element_bl + 7
        # Construct rigid elements
        if type_ == 1:
            self.ele(node_b, node_bl, c, element_bl)
            self.ele(node_lb, node_l, c, element_lb)
            self.ele(node_l, node_lt, c, element_lt)
            self.ele(node_tl, node_t, c, element_tl)
            self.ele(node_t, node_tr, c, element_tr)
            self.ele(node_rt, node_r, c, element_rt)
            self.ele(node_r, node_br, c, element_rb)
            self.ele(node_br, node_b, c, element_br)
        elif type_ == 2:
            self.ele(node_c, node_b, c, element_b)
            self.ele(node_c, node_r, c, element_r)
            if position != "L" and position != "LT":
                self.ele(node_c, node_l, c, element_l)
            if position != "T" and position != "LT" and position != "RT":
                self.ele(node_c, node_t, c, element_t)
        # panel zone spring
        if type_ == 1:
            spring_id = 11000000 + floor * 10000 + axis * 100
            self.zero_length(node_tr, node_rt, "red", spring_id)

    def save(self) -> dict[str, Path]:
        """Persist all generated artifacts and return their paths."""
        model_name = self.frame.frame_name
        output_path = self.frame.output_path
        paths = {
            "tcl": output_path / f"{model_name}.tcl",
            "python": output_path / f"{model_name}.py",
            "json": output_path / f"{model_name}.json",
            "image": output_path / f"{model_name}.png",
            "html": output_path / f"{model_name}.html",
            "information": output_path / f"Model Information_{model_name}.txt",
        }
        conflicts = [path for path in paths.values() if path.exists()]
        if conflicts and not self.overwrite:
            formatted = ", ".join(str(path) for path in conflicts)
            raise FileExistsError(f"Refusing to overwrite existing files: {formatted}")

        self.fig.savefig(paths["image"], dpi=1200)
        if self.show_plot:
            plt.show()
        text_to_write = "\n".join(self.tcl_script)
        text_to_writepy = "\n".join(self.py_script)
        paths["tcl"].write_text(text_to_write, encoding="utf-8")
        paths["python"].write_text(text_to_writepy, encoding="utf-8")
        with paths["json"].open("w", encoding="utf-8") as stream:
            json.dump(self.frame.dict_info, stream, indent=4, ensure_ascii=False)
        from .model_report import write_model_report

        write_model_report(self.frame, paths["html"])
        if self.Nrecorder < 512:
            print("\n----------------- Success -----------------------")
        else:
            print("\n----------------- Warning -----------------------")
        print("The tcl and openseespy scripts were generated successfully")
        if self.Nrecorder >= 512:
            print(
                f"----- But number of recorders ({self.Nrecorder}) exceed the limit of operating system,"
            )
            print("      which may result in the inability to read ground motion files.")
            print("      It suggested to cancel the defination of some unimportant recorders.")
        line1 = self.line_frag["gminfo"][0]
        line2 = self.line_frag["gminfo"][1]
        print(
            f"For the tcl script, the user still need to modify lines {line1} - {line2} to define the ground motion information"
        )
        print("The generated files as follow:")
        for path in paths.values():
            print(path.absolute())
        print("-------------------------------------------------\n")
        return paths
